FROM python:3.8-slim

WORKDIR /app
COPY test_bot_parser.py /app/test_bot_parser.py
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

CMD ["python", "test_bot_parser.py"]
