FROM python:3.8-slim

RUN apt-get update && apt-get install -y postgresql-client
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY job_vacancies.csv /app/data/job_vacancies.csv
COPY . /app

CMD ["python", "./your-script.py"]
